name: interval_timer
description: Tabata timer for fitness

version: 2.0.0+3

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  audioplayers: ^0.14.0

  rxdart: ^0.23.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/sound/pause.mp3
    - assets/sound/work.mp3
    - assets/celebration.png
